In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
x = pd.read_csv("C:/Users/Alex Garriga/Downloads/email-password-recovery-code.csv", header=0).values

In [5]:
print(x)

[['rachel@example.com;9012;12se74;rb9012;Rachel;Booker;Sales;Manchester']
 ['laura@example.com;2070;04ap67;lg2070;Laura;Grey;Depot;London']
 ['craig@example.com;4081;30no86;cj4081;Craig;Johnson;Depot;London']
 ['mary@example.com;9346;14ju73;mj9346;Mary;Jenkins;Engineering;Manchester']
 ['jamie@example.com;5079;09ja61;js5079;Jamie;Smith;Engineering;Manchester']]


In [6]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

In [7]:
print(a)

[[-2.58289208  0.43014843 -1.24082018  1.59572603]
 [ 0.99027828  1.17150989  0.94125714 -0.14692469]
 [ 0.76989341  0.81299683 -0.95068423  0.11769564]
 [ 0.20484034  0.34784527  1.96979195  0.51992837]]


In [8]:
x = pd.read_csv("C:/Users/Alex Garriga/OneDrive/Desktop/AzureDatabricksUdemy/circuits.csv", header=0).values


In [9]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

In [10]:
df = pd.DataFrame(a)
print(df)

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928


In [11]:
df.to_csv('C:/Users/Alex Garriga/OneDrive/Desktop/AzureDatabricksUdemy/pd.csv')

In [18]:
arr2d = np.array([[12, 24, 31], [45, 54, 68]])
print(arr2d)

[[12 24 31]
 [45 54 68]]


In [19]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[14, 26, 34], [45, 56, 67]]])

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[14 26 34]
  [45 56 67]]]


In [16]:
print(arr2d.ndim)
print(arr3d.ndim)

2
3


In [23]:
arr5d = np.array([[1, 2, 3, 4],[6,7,8,9]], ndmin=5)

print(arr5d)
print('number of dimensions :', arr5d.ndim)

[[[[[1 2 3 4]
    [6 7 8 9]]]]]
number of dimensions : 5


In [30]:
print(arr2d[0])
print(arr2d[0,1])
print(arr2d[1])
print(arr2d[1,0])
print(arr2d[1,0]+arr2d[0,1])
print(arr3d[0])
print(arr3d[0,0])
print(arr3d[0,0,0])
print(arr5d[0,0,0])
print(arr5d[0,0,0,1])

[12 24 31]
24
[45 54 68]
45
69
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[[1 2 3 4]
 [6 7 8 9]]
[6 7 8 9]


In [34]:
arr1d=np.array([0,1, 2, 3, 4, 5, 6, 7,8,9,10,11,12,13,14,15])

In [35]:
print(arr1d[1:5])

[1 2 3 4]


In [37]:
print(arr1d[8:])

[ 8  9 10 11 12 13 14 15]


In [38]:
print(arr1d[:5])

[0 1 2 3 4]


In [40]:
print(arr1d[-4:-1])

[12 13 14]


In [44]:
print(arr1d[2:10:2])

[2 4 6 8]


In [45]:
print(arr2d[1, 1:4])

[54 68]


In [46]:
print(arr1d.dtype)

int32


In [48]:
arrstring = np.array(['Ford', 'BMW', 'GMC'])
print(arrstring.dtype)

<U4


In [49]:
arrstring2 = np.array([1, 2, 3, 4,4.5,3.2,2.13], dtype='S')
print(arrstring2)
print(arrstring2.dtype)

[b'1' b'2' b'3' b'4' b'4.5' b'3.2' b'2.13']
|S4


In [52]:
arri4 = np.array([1, 2, 3, 4,4.5,3.2,2.13], dtype='i4')
print(arri4)
print(arri4.dtype)

[1 2 3 4 4 3 2]
int32


In [54]:
arrdec = np.array([1.143, 322.14, 436.12])
print(arrdec)
print(arrdec.dtype)
newarrdec = arrdec.astype('i')

print(newarrdec)
print(newarrdec.dtype)

[  1.143 322.14  436.12 ]
float64
[  1 322 436]
int32


In [58]:
arrint = np.array([1, 0, 3,2,4,5,-1])
print(arrint)
print(arrint.dtype)
newarrint = arrint.astype(bool)

print(newarrint)
print(newarrint.dtype)

[ 1  0  3  2  4  5 -1]
int32
[ True False  True  True  True  True  True]
bool


In [59]:
''' numpy data types and code
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )'''

' numpy data types and code\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )'